import type { FleetManifest, MissionStatus } from '../protocol/types.js';

const STATUS_EMOJI: Record<MissionStatus, string> = {
  'pending':      '⏳',
  'ready':        '🟡',
  'assigned':     '📋',
  'in-progress':  '🔄',
  'completed':    '✅',
  'blocked':      '🚫',
  'stalled':      '⚠️',
  'failed':       '❌',
  'merge-queued': '📦',
  'merged':       '🟢',
};

function countByStatus(missions: FleetManifest['missions'], ...statuses: MissionStatus[]): number {
  return missions.filter((m) => statuses.includes(m.status)).length;
}

function uniqueShips(missions: FleetManifest['missions']): string[] {
  const ships = new Set<string>();
  for (const m of missions) {
    if (m.ship) ships.add(m.ship);
  }
  return [...ships].sort();
}

function computeTotalTimeMin(manifest: FleetManifest): number {
  if (manifest.completed.length < 2) return 0;
  const times = manifest.completed
    .map((c) => new Date(c.mergedDate).getTime())
    .sort((a, b) => a - b);
  return (times[times.length - 1] - times[0]) / (1000 * 60);
}

function estimateTimeSavedMin(manifest: FleetManifest): number {
  // Sequential estimate: each completed mission would take avg duration in sequence.
  // With parallelism, actual wall-clock is totalTime. Saved = sequential - wall.
  const ships = uniqueShips(manifest.missions);
  const parallelism = Math.max(ships.length, 1);
  const totalMin = computeTotalTimeMin(manifest);
  if (totalMin === 0 || manifest.completed.length < 2) return 0;
  const sequentialEstimate = totalMin * parallelism;
  return Math.max(0, Math.round(sequentialEstimate - totalMin));
}

function formatMin(min: number): string {
  if (min < 1) return '< 1 min';
  if (min < 60) return `${Math.round(min)} min`;
  const h = Math.floor(min / 60);
  const m = Math.round(min % 60);
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}

export function generateReport(manifest: FleetManifest): string {
  const lines: string[] = [];
  const now = new Date();

  // Header
  lines.push('# Fleet Run Report');
  lines.push('');
  lines.push(`> Generated: ${now.toISOString()}`);
  lines.push('');

  const total = manifest.missions.length;
  const completed = countByStatus(manifest.missions, 'completed', 'merged', 'merge-queued');
  const inProgress = countByStatus(manifest.missions, 'in-progress', 'assigned');
  const pending = countByStatus(manifest.missions, 'pending', 'ready');
  const failed = countByStatus(manifest.missions, 'failed');
  const ships = uniqueShips(manifest.missions);
  const totalTimeMin = computeTotalTimeMin(manifest);
  const timeSavedMin = estimateTimeSavedMin(manifest);

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Total missions | ${total} |`);
  lines.push(`| Completed | ${completed} |`);
  lines.push(`| In-progress | ${inProgress} |`);
  lines.push(`| Pending | ${pending} |`);
  lines.push(`| Failed | ${failed} |`);
  lines.push(`| Ships used | ${ships.length} |`);
  lines.push(`| Total time | ${formatMin(totalTimeMin)} |`);
  lines.push(`| Est. time saved | ${formatMin(timeSavedMin)} |`);
  lines.push('');

  // Mission table
  lines.push('## Missions');
  lines.push('');

  if (total === 0) {
    lines.push('No missions.');
  } else {
    lines.push('| ID | Branch | Ship | Agent | Status |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const m of manifest.missions) {
      const emoji = STATUS_EMOJI[m.status] ?? '';
      const ship = m.ship ?? '—';
      lines.push(`| ${m.id} | ${m.branch} | ${ship} | ${m.agent} | ${emoji} ${m.status} |`);
    }
  }
  lines.push('');

  // Completed entries
  if (manifest.completed.length > 0) {
    lines.push('## Completed');
    lines.push('');
    lines.push('| Mission | Branch | Merged |');
    lines.push('| --- | --- | --- |');
    for (const c of manifest.completed) {
      const d = new Date(c.mergedDate);
      lines.push(`| ${c.missionId} | ${c.branch} | ${d.toISOString()} |`);
    }
    lines.push('');
  }

  // Merge queue
  if (manifest.mergeQueue.length > 0) {
    lines.push('## Merge Queue');
    lines.push('');
    lines.push('| Mission | Branch | CI Status | Note |');
    lines.push('| --- | --- | --- | --- |');
    for (const e of manifest.mergeQueue) {
      lines.push(`| ${e.missionId} | ${e.branch} | ${e.ciStatus} | ${e.note} |`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [FleetSpark](https://fleetspark.dev)*');

  return lines.join('\n');
}

export function generateReportJson(manifest: FleetManifest): object {
  const total = manifest.missions.length;
  const completed = countByStatus(manifest.missions, 'completed', 'merged', 'merge-queued');
  const inProgress = countByStatus(manifest.missions, 'in-progress', 'assigned');
  const pending = countByStatus(manifest.missions, 'pending', 'ready');
  const failed = countByStatus(manifest.missions, 'failed');
  const ships = uniqueShips(manifest.missions);
  const totalTimeMin = computeTotalTimeMin(manifest);
  const timeSavedMin = estimateTimeSavedMin(manifest);

  return {
    generatedAt: new Date().toISOString(),
    summary: {
      totalMissions: total,
      completed,
      inProgress,
      pending,
      failed,
      shipsUsed: ships.length,
      ships,
      totalTimeMin: Math.round(totalTimeMin),
      estimatedTimeSavedMin: timeSavedMin,
    },
    missions: manifest.missions.map((m) => ({
      id: m.id,
      branch: m.branch,
      ship: m.ship,
      agent: m.agent,
      status: m.status,
      depends: m.depends,
      blocker: m.blocker,
    })),
    completed: manifest.completed.map((c) => ({
      missionId: c.missionId,
      branch: c.branch,
      mergedDate: new Date(c.mergedDate).toISOString(),
    })),
    mergeQueue: manifest.mergeQueue.map((e) => ({
      missionId: e.missionId,
      branch: e.branch,
      ciStatus: e.ciStatus,
      note: e.note,
    })),
  };
}
