import type { GitOps, PRStatus } from '../git/git-ops.js';
import type { FleetManifest, Mission } from '../protocol/types.js';

export interface MergeConfig {
  ciRequired: boolean;
  autoRebase: boolean;
}

export interface MergeResult {
  missionId: string;
  action: 'pr-created' | 'merged' | 'conflict' | 'ci-pending' | 'ci-failed';
  prUrl?: string;
  requiresApproval?: boolean;
}

export class MergeCommander {
  constructor(
    private gitOps: GitOps,
    private config: MergeConfig
  ) {}

  async tick(manifest: FleetManifest): Promise<MergeResult[]> {
    const results: MergeResult[] = [];
    for (const mission of manifest.missions) {
      if (mission.status === 'completed') {
        const result = await this.handleCompleted(mission);
        if (result) results.push(result);
      } else if (mission.status === 'merge-queued') {
        const result = await this.handleMergeQueued(mission);
        if (result) results.push(result);
      }
    }
    return results;
  }

  private async handleCompleted(mission: Mission): Promise<MergeResult | null> {
    const existing = await this.gitOps.getPRStatus(mission.branch);
    if (existing) {
      return this.checkPRStatus(mission, existing);
    }
    const title = `fleet: merge ${mission.id} (${mission.branch})`;
    const body = `Auto-generated by Fleet commander.\n\nMission: ${mission.id}\nBranch: ${mission.branch}`;
    const prUrl = await this.gitOps.createPR(mission.branch, 'main', title, body);
    return { missionId: mission.id, action: 'pr-created', prUrl };
  }

  private async handleMergeQueued(mission: Mission): Promise<MergeResult | null> {
    const prStatus = await this.gitOps.getPRStatus(mission.branch);
    if (!prStatus) {
      return this.handleCompleted(mission);
    }
    return this.checkPRStatus(mission, prStatus);
  }

  private async checkPRStatus(mission: Mission, pr: PRStatus): Promise<MergeResult> {
    if (pr.hasConflicts) {
      return { missionId: mission.id, action: 'conflict', prUrl: pr.url, requiresApproval: true };
    }
    if (this.config.ciRequired) {
      if (pr.ciStatus === 'pending') {
        return { missionId: mission.id, action: 'ci-pending', prUrl: pr.url };
      }
      if (pr.ciStatus === 'failure') {
        return { missionId: mission.id, action: 'ci-failed', prUrl: pr.url };
      }
      if (pr.ciStatus !== 'success' && pr.ciStatus !== 'none') {
        return { missionId: mission.id, action: 'ci-pending', prUrl: pr.url };
      }
    }
    await this.gitOps.mergePR(mission.branch, 'merge');
    return { missionId: mission.id, action: 'merged', prUrl: pr.url };
  }
}
