import type { GitOps, PRStatus } from '../git/git-ops.js';
import type { FleetManifest, Mission } from '../protocol/types.js';
import { ConflictDetector } from './conflict-detector.js';

export interface MergeConfig {
  ciRequired: boolean;
  autoRebase: boolean;
}

export interface MergeResult {
  missionId: string;
  action: 'pr-created' | 'merged' | 'conflict' | 'ci-pending' | 'ci-failed';
  prUrl?: string;
  requiresApproval?: boolean;
}

export class MergeCommander {
  private conflictDetector: ConflictDetector;

  constructor(private gitOps: GitOps, private config: MergeConfig) {
    this.conflictDetector = new ConflictDetector(gitOps);
  }

  async tick(manifest: FleetManifest): Promise<MergeResult[]> {
    const results: MergeResult[] = [];
    for (const mission of manifest.missions) {
      if (mission.status === 'completed') {
        const result = await this.handleCompleted(mission, manifest);
        if (result) results.push(result);
      } else if (mission.status === 'merge-queued') {
        const result = await this.handleMergeQueued(mission, manifest);
        if (result) results.push(result);
      }
    }
    return results;
  }

  private async handleCompleted(mission: Mission, manifest: FleetManifest): Promise<MergeResult | null> {
    const existing = await this.gitOps.getPRStatus(mission.branch);
    if (existing) {
      return this.checkPRStatus(mission, existing);
    }

    // Check for file overlaps with other active branches
    let conflictWarning = '';
    try {
      const report = await this.conflictDetector.check(mission, manifest.missions);
      if (report.overlappingFiles.length > 0) {
        const files = report.overlappingFiles
          .map((o) => `- \`${o.file}\` (also modified on \`${o.conflictsWith}\`)`)
          .join('\n');
        conflictWarning = `\n\n⚠️ **File overlap detected:**\n${files}`;
      }
    } catch {
      // Non-blocking — proceed without conflict info
    }

    const title = `fleet: merge ${mission.id} (${mission.branch})`;
    const body = `Auto-generated by Fleet commander.\n\nMission: ${mission.id}\nBranch: ${mission.branch}${conflictWarning}`;
    const prUrl = await this.gitOps.createPR(mission.branch, 'main', title, body);
    return { missionId: mission.id, action: 'pr-created', prUrl };
  }

  private async handleMergeQueued(mission: Mission, manifest: FleetManifest): Promise<MergeResult | null> {
    const prStatus = await this.gitOps.getPRStatus(mission.branch);
    if (!prStatus) {
      return this.handleCompleted(mission, manifest);
    }
    return this.checkPRStatus(mission, prStatus);
  }

  private async checkPRStatus(mission: Mission, pr: PRStatus): Promise<MergeResult> {
    if (pr.hasConflicts) {
      return { missionId: mission.id, action: 'conflict', prUrl: pr.url, requiresApproval: true };
    }
    if (this.config.ciRequired) {
      if (pr.ciStatus === 'pending') {
        return { missionId: mission.id, action: 'ci-pending', prUrl: pr.url };
      }
      if (pr.ciStatus === 'failure') {
        return { missionId: mission.id, action: 'ci-failed', prUrl: pr.url };
      }
      if (pr.ciStatus !== 'success' && pr.ciStatus !== 'none') {
        return { missionId: mission.id, action: 'ci-pending', prUrl: pr.url };
      }
    }
    await this.gitOps.mergePR(mission.branch, 'merge');
    return { missionId: mission.id, action: 'merged', prUrl: pr.url };
  }
}
