import { describe, it, expect } from 'vitest';
import { generateReport, generateReportJson } from '../../../packages/core/dist/report/report-generator.js';

function makeManifest(overrides: Record<string, unknown> = {}) {
  return {
    updated: new Date('2026-03-23T10:00:00Z'),
    commander: {
      host: 'dev-machine',
      lastCheckin: new Date(),
      status: 'active' as const,
      timeoutMinutes: 30,
    },
    missions: [
      { id: 'M1', branch: 'feat/auth', ship: 'ship-1', agent: 'claude', status: 'in-progress' as const, depends: [], blocker: '' },
      { id: 'M2', branch: 'feat/api', ship: 'ship-2', agent: 'claude', status: 'pending' as const, depends: [], blocker: '' },
      { id: 'M3', branch: 'feat/ui', ship: 'ship-1', agent: 'claude', status: 'completed' as const, depends: [], blocker: '' },
      { id: 'M4', branch: 'fix/crash', ship: 'ship-3', agent: 'claude', status: 'failed' as const, depends: [], blocker: '' },
      { id: 'M5', branch: 'feat/docs', ship: null, agent: 'claude', status: 'merged' as const, depends: [], blocker: '' },
    ],
    mergeQueue: [],
    completed: [
      { missionId: 'M3', branch: 'feat/ui', mergedDate: new Date('2026-03-23T10:30:00Z') },
      { missionId: 'M5', branch: 'feat/docs', mergedDate: new Date('2026-03-23T11:00:00Z') },
    ],
    ...overrides,
  };
}

describe('generateReport', () => {
  it('returns a markdown string with header', () => {
    const report = generateReport(makeManifest());
    expect(report).toContain('# Fleet Run Report');
    expect(report).toContain('Generated:');
  });

  it('includes mission table with IDs, branches, and ships', () => {
    const report = generateReport(makeManifest());
    expect(report).toContain('| ID | Branch | Ship | Agent | Status |');
    expect(report).toContain('M1');
    expect(report).toContain('feat/auth');
    expect(report).toContain('ship-1');
    expect(report).toContain('M2');
    expect(report).toContain('feat/api');
    expect(report).toContain('ship-2');
  });

  it('includes summary metrics', () => {
    const report = generateReport(makeManifest());
    expect(report).toContain('## Summary');
    expect(report).toContain('Total missions');
    expect(report).toContain('| 5 |');
    expect(report).toContain('In-progress');
    expect(report).toContain('Pending');
    expect(report).toContain('Failed');
    expect(report).toContain('Ships used');
    expect(report).toContain('Total time');
    expect(report).toContain('Est. time saved');
  });

  it('counts unique ships correctly', () => {
    const json = generateReportJson(makeManifest()) as Record<string, any>;
    // ship-1, ship-2, ship-3 (M5 has ship=null, not counted)
    expect(json.summary.shipsUsed).toBe(3);
    expect(json.summary.ships).toEqual(['ship-1', 'ship-2', 'ship-3']);
  });

  it('handles empty manifest gracefully', () => {
    const empty = makeManifest({ missions: [], completed: [], mergeQueue: [] });
    const report = generateReport(empty);
    expect(report).toContain('# Fleet Run Report');
    expect(report).toContain('No missions');
    expect(report).toContain('| 0 |');

    const json = generateReportJson(empty) as Record<string, any>;
    expect(json.summary.totalMissions).toBe(0);
    expect(json.missions).toEqual([]);
  });

  it('shows failed missions with fail emoji', () => {
    const report = generateReport(makeManifest());
    // M4 is failed — look for the fail indicator on its row
    const lines = report.split('\n');
    const failLine = lines.find((l) => l.includes('M4') && l.includes('fix/crash'));
    expect(failLine).toBeDefined();
    expect(failLine).toContain('failed');
  });

  it('includes fleetspark.dev link in footer', () => {
    const report = generateReport(makeManifest());
    expect(report).toContain('*Generated by [FleetSpark](https://fleetspark.dev)*');
  });
});
